### ISSUE TITLE
Identifier 'h' has already been declared

### ISSUE THREAD

**Issue by amirharel-fyber** [developit/preact#1010]
I have a project with `rollup`, `preact`, `preact-compat`.
All worked fine, until i added `preact-portal` and then i got this error:
```
[!] (commonjs plugin) SyntaxError: Identifier 'h' has already been declared (2:9) in /Users/amir/projects/reacttag/node_modules/preact-portal/src/preact-portal.js
node_modules/preact-portal/src/preact-portal.js (2:9)
SyntaxError: Identifier 'h' has already been declared (2:9) in /Users/amir/projects/reacttag/node_modules/preact-portal/src/preact-portal.js
    at error (/Users/amir/projects/reacttag/node_modules/rollup/dist/rollup.js:168:15)
    at /Users/amir/projects/reacttag/node_modules/rollup/dist/rollup.js:17955:17
```

Here is my rollup config:
```javascript
// rollup.config.js
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import sass from 'rollup-plugin-sass';
import replace from  'rollup-plugin-replace';

export default {
  input: 'src/main.js',
  output: {
    file: 'dist/bundle.dev.js',
    format: 'iife',
    name: 'MyLib',
    sourcemap: 'inline',
  },
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    }),
    sass({
      insert: true
    }),
    babel({
      'exclude': [
        'node_modules/preact/**',
        'node_modules/preact-compat/**'
      ]
    }),
    resolve({
      browser: true,
      jsnext: true,
      extensions: ['.js', '.jsx']
    }),
    commonjs({
      namedExports: {
        './node_modules/preact/dist/preact.js': [
          'h',
          'render',
          'Component',
          'cloneElement',
          'options'
        ],
        './node_modules/react/react.js': [
          'cloneElement',
          'createElement',
          'PropTypes',
          'Children',
          'PureComponent',
          'Component',
          'isValidElement'
        ],
        'node_modules/redux-logger/dist/redux-logger.js': [
          'createLogger'
        ]
      }
    }),
  ]
};
```

and my babelrc:
```javascript
{
  "env": {
    "build": {
      "presets": ["flow", "react"],
      "plugins": [
        [
          "transform-react-jsx",
          {
            "pragma": "h"
          }
        ],
        [
          "babel-plugin-jsx-pragmatic", {
          "module": "preact",
          "import": "h",
          "export": "h"
        }
        ],
        [
          "module-resolver",
          {
            "alias": {
              "react": "preact-compat",
              "react-dom": "preact-compat",
              "react-addons-transition-group": "preact-transition-group",
              "react-addons-css-transition-group": "preact-css-transition-group",
              "indexof": "component-indexof"
            }
          }
        ],
        "transform-class-properties",
        "transform-object-rest-spread",
        "external-helpers"
      ]
    }
}
```

Any idea what is the problem?

**Comment by developit** [comment]
You're importing `{ h }` from Preact, but using `babel-plugin-jsx-pragmatic`.

I would recommend using one or the other, but not both.

**Comment by amirharel-fyber** [comment]
@developit where do i import `{ h }` from Preact? 
You mean from the `commonjs` plugin? 

```
'./node_modules/preact/dist/preact.js': [
          'h',
          'render',
          'Component',
          'cloneElement',
          'options'
        ],
``` 
should i remove this h from there? because i tried it and it didn't work.

**Comment by developit** [comment]
You can just remove the whole jsx-pragmatic plugin from your `babelrc`:

```diff
-        [
-          "babel-plugin-jsx-pragmatic", {
-          "module": "preact",
-          "import": "h",
-          "export": "h"
-        }
-        ],
```

**Comment by andrebautista** [comment]
Using the following `.babelrc` configuration I still need to import h into every component. Is this to be expected? If I add `babel-plugin-jsx-pragmatic` then I no longer need to import it into every component.
```
   plugins: [
        "transform-object-rest-spread",
        "transform-class-properties",
        "transform-decorators",
        "syntax-dynamic-import",
        ["transform-react-jsx", { "pragma": "h" }]
    ]```

**Comment by marvinhagemeister** [comment]
See developit's comment above. That's the whole point of `babel-plugin-jsx-pragmatic` that you do not have to import `h` yourself.
